Feature/include headers in api response
carrier-io/carrier-auth pull request #12
Opened 2021-04-27 15:29 UTC by Aspect13

Now retirning entity enriched with id from keycloak upon creating one or returning 'id' as a dict key with received value

2021-04-28 11:22 UTC, arozumenko requested changes

2021-04-28 11:22 UTC, arozumenko commented on requirements.txt
> +requests
please put version here

2021-05-18 14:29 UTC, Aspect13 commented on requirements.txt
> +requests
done

2021-05-18 16:52 UTC, arozumenko approved these changes

2021-05-18 16:52 UTC, merged